#!/usr/bin/env python3

import argparse
import csv
import sys

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Converts a CSV file into a Markdown table")
    parser.add_argument("input", nargs='?', help="Input file")
    parser.add_argument("output", nargs='?', help="Output file")
    args = parser.parse_args()

    output = ""
    col_width = dict()

    try:
        if args.input and args.input != "-":
            f = open(args.input, 'r')
        else:
            print("Reading from stdin...", file=sys.stderr)
            f = sys.stdin

        csv_reader = csv.reader(f, delimiter=',', quotechar='"')
        table = []
        for row in csv_reader:
            cloned_row = []
            for i in range(len(row)):
                width = col_width.get(i, 0)
                col_width[i] = max(width, len(row[i]))
                cloned_row.append(row[i])
            table.append(cloned_row)

        first = True
        for row in table:
            output += "|"
            for i in range(len(row)):
                output += " {} |".format(row[i].ljust(col_width[i]))
            output += "\n"

            if first:
                first = False
                output += "|"
                for i in range(len(row)):
                    output += "-" * (col_width[i] + 2)
                    output += "|"
                output += "\n"
    finally:
        if args.input:
            f.close()

    if args.output:
        with open(args.output, 'w') as f:
            f.write(output)
    else:
        print(output, end="")
